{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Release.Namespace }}"
  annotations:
    # if deployed via argocd and/or helm, prevent the namespace getting deleted
    helm.sh/resource-policy: "keep"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    {{- if .Values.namespace.secure }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    {{- end }}
    {{- if .Values.namespace.labels }}
    {{- .Values.namespace.labels | toYaml | nindent 4 }}
    {{- end }}
{{- end }}