apiVersion: v2
name: azul-infra
description: Azul optional infrastructure components

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "11.0.0-unstable"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "11.0.0-unstable"

dependencies:
  - name: loki
    version: "18.8.0"
    # repository: https://grafana-community.github.io/helm-charts
    repository: file://charts/loki-18.8.0.tgz
    condition: loki.enable
  - name: kube-prometheus-stack
    version: "88.3.0"
    # repository: https://prometheus-community.github.io/helm-charts
    repository: file://charts/kube-prometheus-stack-88.3.0.tgz
    condition: kube-prometheus-stack.enable
  - name: prometheus-blackbox-exporter
    version: "11.17.2"
    # repository: https://prometheus-community.github.io/helm-charts
    repository: file://charts/prometheus-blackbox-exporter-11.17.2.tgz
    condition: prometheus-blackbox-exporter.enable
  - name: prometheus-pushgateway
    version: "3.8.0"
    # repository: https://prometheus-community.github.io/helm-charts
    repository: file://charts/prometheus-pushgateway-3.8.0.tgz
    condition: prometheus-pushgateway.enable
  - name: seaweedfs
    version: 4.41.0
    # repository: https://seaweedfs.github.io/seaweedfs/helm
    repository: file://charts/seaweedfs-4.41.0.tgz
    condition: seaweedfs-main.enabled
    alias: seaweedfs-main
  - name: seaweedfs
    version: 4.41.0
    # repository: https://seaweedfs.github.io/seaweedfs/helm
    repository: file://charts/seaweedfs-4.41.0.tgz
    condition: seaweedfs-backup.enabled
    alias: seaweedfs-backup