{
 "title": "Opensearch Summary",
 "description": "Summary of Opensearch stats",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "azul_namespace",
    "query": {
     "query": "label_values(opensearch_shard_size,kubernetes_namespace)"
    }
   },
   {
    "name": "opensearch_namespace",
    "label": "opensearch_namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{pod=~\".*opensearch-nodes.*\"},namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Opensearch Stats\n\nThis dashboard displays summary information about the Opensearch cluster.\n\nThis includes the number and size of the shards and the RAM/CPU used by the Opsearch nodes."
   }
  },
  {
   "title": "Cluster Info Summary",
   "type": "table",
   "description": "Summary information about the cluster's health.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "opensearch_health_info_summary_info{kubernetes_namespace=\"$azul_namespace\"}"
    }
   ]
  },
  {
   "title": "Opensearch RAM Usage (Allocated/Active)",
   "type": "timeseries",
   "description": "Total RAM used by Opensearch nodes split into active and allocated RAM.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_total_active_file_bytes{namespace=\"$opensearch_namespace\",container=\"opensearch\",pod=~\"azul-opensearch-nodes-.*\",service=\"kube-prometheus-stack-kubelet\"}",
     "legendFormat": "active-{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$opensearch_namespace\",container=\"opensearch\",pod=~\"azul-opensearch-nodes-.*\",service=\"kube-prometheus-stack-kubelet\"}",
     "legendFormat": "allocated-{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Opensearch Node CPU usage over time (ms)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"infra-qa\",container=\"opensearch\",pod=~\"azul-opensearch-nodes-.*\",service=\"kube-prometheus-stack-kubelet\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shard Summary",
   "type": "table",
   "description": "Summary of the shard storage usage.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(opensearch_shard_size{kubernetes_namespace=\"$azul_namespace\"}) by (index,shard,node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index shard sizes",
   "type": "timeseries",
   "description": "Displays all indices and their shard sizes.\nEach index/shard combination has all of it's primaries and secondaries listed separately.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(opensearch_shard_size{kubernetes_namespace=\"$azul_namespace\"}) by (index,shard,node)",
     "legendFormat": "{{index}}-{{shard}}"
    }
   ]
  }
 ]
}