{
 "title": "Consumers/Producers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard show the timings within common dispatcher requests that involve kafka.\nIt can be used to spot bottlenecks and areas where performance can be improved.\n\nView the dispatcher code to match stage/pipeline names with what they are trying to achieve.\n\n* consume - A plugin or metastore-ingestor is asking for events to process\n* produce - A plugin or metastore is giving events to dispatcher\n* stage - a request is broken down into stages\n* pipeline - the 'pipeline' processing stage is composed of several specific pipeline actions\nto transform events\n\n"
   }
  },
  { "title": "Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Runs - Consume Stages",
   "type": "timeseries",
   "description": "Generally, all stages should have the same run count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_consume_duration_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs - Producer Stages",
   "type": "timeseries",
   "description": "Generally, all stages should have the same run count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_produce_duration_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runtime - Consume Stages",
   "type": "timeseries",
   "description": "Shows stages that caused the most cumulative delays in response to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_consume_duration_sum{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runtime - Produce Stages",
   "type": "timeseries",
   "description": "Shows stages that caused the most cumulative delays in response to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_produce_duration_sum{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Runtime - Consume Stages",
   "type": "heatmap",
   "description": "99% of runs will complete before this time. Hide <100µs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dispatcher_events_consume_duration_bucket{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (le, stage))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Runtime - Produce Stages",
   "type": "heatmap",
   "description": "99% of runs will complete before this time. Hide <100µs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dispatcher_events_produce_duration_bucket{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (le, stage))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Consume Pipeline Errors",
   "type": "timeseries",
   "description": "Shows errors that occur during pipelines that transform events from kafka into valid formats for clients.\nErrors here may indicate that documents in kafka are corrupt or a pipeline has bugs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "count_over_time({component=\"dispatcher\", category=\"consumer\", subset=\"err\", namespace=\"$namespace\"} | json user_agent=\"user_agent\", pipeline=\"pipeline\" | __error__=`` [10m])",
     "legendFormat": "{{user_agent}} - {{pipeline}}"
    }
   ]
  },
  {
   "title": "Produce Pipeline Errors",
   "type": "timeseries",
   "description": "Shows errors raised during pipelines and the corresponding client that produced those events. Errors here indicate invalid data submitted by clients or bugs in pipelines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "count_over_time({component=\"dispatcher\", category=\"producer\", subset=\"err\", namespace=\"$namespace\"} | json user_agent=\"user_agent\", pipeline=\"pipeline\" | __error__=`` [10m])",
     "legendFormat": "{{user_agent}} - {{pipeline}}"
    }
   ]
  },
  {
   "title": "Last 10 Consume Pipeline Errors",
   "type": "logs",
   "description": "Shows errors raised during pipelines and the corresponding client that produced those events. Errors here indicate invalid data submitted by clients or bugs in pipelines.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{component=\"dispatcher\", category=\"consumer\", subset=\"err\", namespace=\"$namespace\"} | json | line_format `{{.time}} {{.pipeline}} {{.event_bytes}} {{.user_agent}} | {{.description}} | {{.error}}` | __error__=``",
     "legendFormat": "{{user_agent}} - {{pipeline}} - {{description}} - {{error}}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Last 10 Produce Pipeline Errors",
   "type": "logs",
   "description": "Shows errors raised during pipelines and the corresponding client that produced those events. Errors here indicate invalid data submitted by clients or bugs in pipelines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "{component=\"dispatcher\", category=\"producer\", subset=\"err\", namespace=\"$namespace\"} | json | line_format `{{.time}} {{.pipeline}} {{.event_bytes}} {{.user_agent}} | {{.description}} | {{.error}}` | __error__=``",
     "legendFormat": "{{user_agent}} - {{pipeline}} - {{description}} - {{error}}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Runs - Consume Pipelines",
   "type": "timeseries",
   "description": "Pipeline run count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_consume_pipelines_duration_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs - Produce Pipelines",
   "type": "timeseries",
   "description": "Pipeline run count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_produce_pipelines_duration_count{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runtime - Consume Pipelines",
   "type": "timeseries",
   "description": "Shows pipelines that caused the most cumulative delays in response to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_consume_pipelines_duration_sum{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Runtime - Produce Pipelines",
   "type": "timeseries",
   "description": "Shows pipelines that caused the most cumulative delays in response to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_produce_pipelines_duration_sum{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Runtime - Consume Pipelines",
   "type": "heatmap",
   "description": "99% of runs will complete before this time. Hide <100µs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dispatcher_events_consume_pipelines_duration_bucket{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (le, pipeline))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Runtime - Produce Pipelines",
   "type": "heatmap",
   "description": "99% of runs will complete before this time. Hide <100µs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dispatcher_events_produce_pipelines_duration_bucket{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (le, pipeline))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipeline Event Modifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Consumer Pipelines - Filtered Events",
   "type": "timeseries",
   "description": "Pipelines can skip events read from kafka.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_consume_pipelines_removed{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Pipelines - Added Events",
   "type": "timeseries",
   "description": "Pipelines can turn one event into many.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_produce_pipelines_added{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Pipelines - Removed Events",
   "type": "timeseries",
   "description": "Pipelines can remove events supplied by clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_produce_pipelines_removed{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (pipeline)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}