{
 "title": "Metastore Ingestor De-duplication",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Metastore Ingestor De-duplication\nA metastore ingestor dashboard with more detailed information for debugging purposes<br>"
   }
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Event Ingestion Failures / interval",
   "type": "timeseries",
   "description": "Total ingestion with status != success",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(azul_ingest_total{status!=\"success\",kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (type, status, plugin)",
     "legendFormat": "{{type}} {{plugin}} {{status}}"
    }
   ]
  },
  {
   "title": "Event Ingestion / second",
   "type": "timeseries",
   "description": "The rate per second of all event ingestion by Azul",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(azul_ingest_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (type, status)",
     "legendFormat": "{{type}}: {{status}}"
    }
   ]
  },
  { "title": "Ingestion De-duplication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Ingestion De-duplication",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "options": {
    "content": "Ingestion de-duplication occurs when one of Azul's ingestors discards information.\r\nThese pie charts are useful in diagnosing complex issues that may arise where\r\nevents leave a plugin and make it into Kafka.<br/>\r\nAnd then the event doesn't get to Opensearch as expected.<br/>\r\nThis pie chart allows you to verify if events are potentially being discarded for the\r\nplugin you are investigating.<br/>"
   }
  },
  {
   "title": "Status Deduplication",
   "type": "piechart",
   "description": "Total status duplicated events dropped during ingestion.\nThe older event is dropped when a duplicate is found, it typically occurs when a binary is processed twice in quick succession by a plugin.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_duplicates_total{kubernetes_namespace=\"$namespace\", type=\"status\"}) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Binary Deduplication",
   "type": "piechart",
   "description": "Total binary duplicated events dropped during ingestion.\nThe older event is dropped when a duplicate is found, binary duplication is rare and normally occurs with non-standard plugins.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_duplicates_total{kubernetes_namespace=\"$namespace\", type=\"binary\"}) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Plugin Deduplication",
   "type": "piechart",
   "description": "Total status duplicated events dropped during ingestion.\nPlugin duplication typically occurs when multiple instances of a plugin all start at the same time.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_duplicates_total{kubernetes_namespace=\"$namespace\", type=\"plugin\"}) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  }
 ]
}