{
 "title": "Processing",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Events - Processing\nThis dashboard displays plugin events processing information<br>"
   }
  },
  {
   "title": "Dispatcher Process Memory",
   "type": "stat",
   "description": "Memory usage per Dispatcher Kubernetes instance",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=~\"dp-.*\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Dedupe Hit Ratio",
   "type": "stat",
   "description": "Percentage of messages successfully skipped due to being duplicates (different to result caching).  Higher is better, if your system expects duplicates.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dispatcher_dedupe_hits_total{kubernetes_namespace=\"$namespace\"}[5m]) / rate(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Dedupe Collision Ratio",
   "type": "stat",
   "description": "Detected collision rate in dedupe cache.  i.e. a previous value is evicted for same slot.  Lower is better.  If rate is high, cache size may need increasing.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dispatcher_dedupe_collisions_total{kubernetes_namespace=\"$namespace\"}[5m]) / rate(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Metastore Binary Ingestion",
   "type": "timeseries",
   "description": "Events per second ingested into Opensearch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_fetched_total{plugin=~\"ingestor.*\", entity=\"binary\", kubernetes_namespace=\"$namespace\"}[5m])) by (plugin, entity)",
     "legendFormat": "{{plugin}}-{{entity}}"
    }
   ]
  },
  {
   "title": "Error Probability Per Plugin",
   "type": "timeseries",
   "description": "Plugin error probability",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_status_published{status=~\"error-.*\", kubernetes_namespace=\"$namespace\"}[$__range])) by (plugin) / sum(increase(dispatcher_events_status_published{status=~\"error-.*|completed|completed-empty\", kubernetes_namespace=\"$namespace\"}[$__range])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Consumer Message Lag (Live)",
   "type": "bargauge",
   "description": "Consumer message lag for Live",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(consumer_group) (burrow_kafka_consumer_lag_total{consumer_group=~\".*-live\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Consumer Message Lag (Expedite)",
   "type": "bargauge",
   "description": "Consumer message lag for Expedite",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(consumer_group) (burrow_kafka_consumer_lag_total{consumer_group=~\".*-expedite\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Consumer Message Lag (Historic)",
   "type": "bargauge",
   "description": "Consumer message lag for Retries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(consumer_group) (burrow_kafka_consumer_lag_total{consumer_group=~\".*-historic\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Bytes to/from Brokers",
   "type": "timeseries",
   "description": "Total bytes to and from Dispatcher and Kafka",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_kafka_produced_message_bytes_total{kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Bytes Out"
    },
    {
     "expr": "sum(rate(dispatcher_kafka_consumed_message_bytes_total{kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Bytes In"
    }
   ]
  },
  {
   "title": "Consumer Message Lag (Retries)",
   "type": "bargauge",
   "description": "Consumer message lag for Retries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(consumer_group) (burrow_kafka_consumer_lag_total{consumer_group=~\".*-retries\", kubernetes_namespace=\"$namespace\"}))",
     "legendFormat": "{{exported_name}}"
    }
   ]
  }
 ]
}