{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows an overview of published & consumed events\nflowing through dispatcher.\n\nIt can be used to diagnose general & specific problems with plugin\nexecution, and identify plugins that are publishing events at a high rate\ncompared to others."
   }
  },
  {
   "title": "Published Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(dispatcher_events_published_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Filtered Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(dispatcher_events_filtered_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consumed Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate(dispatcher_events_fetched_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Plugin Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{status=~\"completed\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Plugin Completed Empty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{status=\"completed-empty\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Plugin Partial Completions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{status=\"completed-with-errors\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Plugin Opt-Outs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{status=\"opt-out\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Plugin Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{status=~\"error-.*\",kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Follow-on-Processing Events Published by Plugins",
   "type": "gauge",
   "description": "Total number of events published by plugins that will cause other plugins to execute. This is computed over the whole time range currently selected.\nThis does not distinguish between events with/out 'data' so overall processing may be lower.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_published_total{kubernetes_namespace=\"$namespace\", entity=~\"binary.*\", entity!=\"binary_enriched\", entity!=\"binary_mapped\"}[$__range])) by (plugin) > 0",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Failed Plugin Kafka Subscriptions",
   "type": "timeseries",
   "description": "Shows number of topics that a plugin has subscribed to that kafka cannot yet supply events from.\nIf this persists, then events from that topic will never be consumed and indicates something bad going on with kafka/dispatcher.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(plugin) (min_over_time(dispatcher_events_consume_not_ready{kubernetes_namespace=\"$namespace\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Event Rate by Plugin",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum (rate(dispatcher_events_fetched_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (plugin)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Tasks Currently Processing",
   "type": "timeseries",
   "description": "A task is an event assigned to a plugin for execution.\nGraph shows number of entries in tasks tracked in Redis.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Tasks" } },
   "targets": [
    {
     "expr": "sum(dispatcher_events_redis_tracking{kubernetes_namespace=\"$namespace\"})\r\n",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Published Event Rate by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum (rate(dispatcher_events_published_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (entity)",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Task State Changes",
   "type": "timeseries",
   "description": "Tasks are started and finished, but can also be lost. \nDue to multiplugins, more events should be completed than dequeued.\nGraph is logarithmic to be able to show low rates of lost tasks.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_redis_tracking_control{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (origin)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published Binary Event Rate by Plugin + Event",
   "type": "timeseries",
   "description": "The number of binary events published per plugin & event type combination.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_published_total{kubernetes_namespace=\"$namespace\", entity=~\"binary\"}[$__rate_interval])) by (plugin, entity)",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Produced Status Rates per Plugin",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (plugin, status)",
     "legendFormat": "{{plugin}} - {{status}}"
    }
   ]
  },
  {
   "title": "Published Complex Event Rate by Plugin + Event",
   "type": "timeseries",
   "description": "The number of non-core event types published by different plugins.\nThese are usually a custom format chosen for the specific plugin.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_published_total{kubernetes_namespace=\"$namespace\", entity!=\"binary\", entity!=\"status\", entity!=\"plugin\"}[$__rate_interval])) by (plugin, event, entity)",
     "legendFormat": "{{plugin}} - {{entity}} - {{event}}"
    }
   ]
  }
 ]
}