{
 "title": "Per Plugin",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "plugin",
    "query": {
     "query": "label_values(dispatcher_events_status_published,plugin)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "# Events - Per Plugin\nThis dashboard displays plugin event information<br>"
   }
  },
  {
   "title": "$plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "plugin",
   "targets": [
    {}
   ]
  },
  {
   "title": "Q1 Expedite",
   "type": "stat",
   "description": "Events waiting to process",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{consumer_group=~\".*$plugin.*-expedite\", kubernetes_namespace=\"$namespace\"}) by (consumer_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Q2 Live",
   "type": "stat",
   "description": "Events waiting to process. If live queue is high, plugin is not running quickly enough. Scale instances or improve code.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{consumer_group=~\".*$plugin.*-live\", kubernetes_namespace=\"$namespace\"}) by (consumer_group)"
    }
   ]
  },
  {
   "title": "Q3 Historic",
   "type": "stat",
   "description": "Events waiting to process. Large numbers are expected after plugins are updated.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{consumer_group=~\".*$plugin.*-historic\", kubernetes_namespace=\"$namespace\"}) by (consumer_group)"
    }
   ]
  },
  {
   "title": "Q4 Retries",
   "type": "stat",
   "description": "Events waiting to process",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{consumer_group=~\".*$plugin.*-retries\", kubernetes_namespace=\"$namespace\"}) by (consumer_group)"
    }
   ]
  },
  {
   "title": "Success Results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"completed.*\", kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"error-.*\", kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Probability",
   "type": "stat",
   "description": "Likelihood that a random relevant event will raise an error. errors / (errors + successes)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"error-.*\", kubernetes_namespace=\"$namespace\"}[$__range])) / sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"completed.*|error-.*\", kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Filtered Events/s",
   "type": "stat",
   "description": "Events from kafka that are filtered before sending to plugin.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_filtered_total{plugin=\"$plugin\", reason=\"filtered\", kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Fetched Events/s",
   "type": "stat",
   "description": "Events from kafka that pass filtering checks and are sent to plugin",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_fetched_total{plugin=\"$plugin\", kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Optout %",
   "type": "stat",
   "description": "Probability plugin will opt out of processing.\nHigh rate means that plugin filters are not restricted enough, or file type identification needs improvement.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"opt-out\", kubernetes_namespace=\"$namespace\"}[$__range]))/sum(increase(dispatcher_events_status_published{plugin=\"$plugin\", status=~\"completed.*|opt-out\", kubernetes_namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50",
   "type": "stat",
   "description": "50% of events process within this time",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(dispatcher_processing_time_seconds_bucket{publisher=\"$plugin\", kubernetes_namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "description": "90% of events process within this time",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.90, sum(rate(dispatcher_processing_time_seconds_bucket{publisher=\"$plugin\", kubernetes_namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99.9",
   "type": "stat",
   "description": "99.9% of events process within this time. Large times are fine if live queue is keeping up.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.999, sum(rate(dispatcher_processing_time_seconds_bucket{publisher=\"$plugin\", kubernetes_namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}