{
 "title": "Azul Resource Usage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows k8s real resource usage.\n\n* Summary information per Azul core service and plugin.\n* Info about real resource usage vs resource requests and limits.\n* Per pod for azul core and plugins."
   }
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory usage Total",
   "type": "timeseries",
   "description": "Total memory usage of the Azul instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"\", pod=~\"plugin-.*\"})",
     "legendFormat": "Plugins"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"\", pod!~\"plugin-.*\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "timeseries",
   "description": "Total CPU usage of the Azul instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"\", pod=~\"plugin-.*\"}[5m]))",
     "legendFormat": "Plugins"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"\", pod!~\"plugin-.*\"}[5m]))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"\"}[5m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory usage per Core Service",
   "type": "timeseries",
   "description": "Memory usage per Azul core service. Due to the regex used to derive service name, this may be missing some pods. As this combines multiple pods, consider checking per-pod information as well.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod!~\"plugin-.*\", container=\"\"}, \"deployment\", \"$1\", \"pod\", \"(?:plugin-)?([^0-9\\n]*)-.*\")) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core Service",
   "type": "timeseries",
   "description": "CPU usage per Azul core service. Due to the regex used to derive service name, this may be missing some pods. As this combines multiple pods, consider checking per-pod information as well.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!~\"plugin-.*\", container=\"\"}[5m]), \"deployment\", \"$1\", \"pod\", \"(?:plugin-)?([^0-9\\n]*)-.*\")) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage per Plugin",
   "type": "timeseries",
   "description": "Memory usage per Azul plugin. Due to the regex used to derive names, this may be missing some pods. As this combines multiple pods, consider checking per-pod information as well.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"plugin-.*\", container=\"\"}, \"deployment\", \"$1\", \"pod\", \"(?:plugin-)?([^0-9\\n]*)-.*\")) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Plugin",
   "type": "timeseries",
   "description": "CPU usage per Azul plugin. Due to the regex used to derive names, this may be missing some pods. As this combines multiple pods, consider checking per-pod information as well.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"plugin-.*\", container=\"\"}[5m]), \"deployment\", \"$1\", \"pod\", \"(?:plugin-)?([^0-9\\n]*)-.*\")) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Resource Request and Limit Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Memory Usage over 90% of Limit (Core)",
   "type": "timeseries",
   "description": "If pods/containers are listed here frequently, consider allocating more memory. Check to see if the pods are crashing, as this indicates allocated memory is insufficient.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{namespace=\"$namespace\", pod!~\"plugin-.*\", container!=\"\"}) by (pod,container))/on(pod,container) group_right() (max(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod!~\"plugin-.*\", container!=\"\"}) by (pod,container)) > 0.9",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage over 90% of Limit (Plugins)",
   "type": "timeseries",
   "description": "If pods/containers are listed here frequently, consider allocating more memory. Check to see if the pods are crashing, as this indicates allocated memory is insufficient.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"plugin-.*\", container!=\"\"}) by (pod,container))/on(pod,container) group_right() (max(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"plugin-.*\", container!=\"\"}) by (pod,container)) > 0.9",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage less than 10% of Request (Core)",
   "type": "timeseries",
   "description": "If pods/containers are listed here frequently, they are using significantly lower memory than requested. This may indicate an over-allocation of memory in k8s configuration.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{namespace=\"$namespace\", pod!~\"plugin-.*\", container!=\"\"}) by (pod,container))/on(pod,container) group_right() (max(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod!~\"plugin-.*\", container!=\"\"}) by (pod,container)) < 0.1",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage less than 10% of Request (Plugins)",
   "type": "timeseries",
   "description": "If pods/containers are listed here frequently, they are using significantly lower memory than requested. This may indicate an over-allocation of memory in k8s configuration.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"plugin-.*\", container!=\"\"}) by (pod,container))/on(pod,container) group_right() (max(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"plugin-.*\", container!=\"\"}) by (pod,container)) < 0.1",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Per Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage per Pod (Core)",
     "type": "timeseries",
     "description": "Memory usage per Azul core service pod.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod!~\"plugin-.*\", container=\"\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage per Pod (Core)",
     "type": "timeseries",
     "description": "CPU usage per Azul core service pod.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!~\"plugin-.*\", container=\"\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage per Pod (Plugins)",
     "type": "timeseries",
     "description": "Memory usage per Azul plugin pod.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"plugin-.*\", container=\"\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage per Pod (Plugins)",
     "type": "timeseries",
     "description": "CPU usage per Azul plugin pod.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"plugin-.*\", container=\"\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}