{
 "title": "Metastore Ingestor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   { "name": "LogFilters" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Metastore\nThis dashboard displays event ingestion<br>"
   }
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Kafka Consumer lag",
   "type": "stat",
   "description": "Ingestor lag in the kafka topics.\nThere should be 3 for binary and 1 for plugins and statuses.\n\nThe smaller the lag the more quickly results are available to the UI as they are published.\nHowever the most important thing is that the number are steady and aren't growing as that means that Opensearch or the Ingestors are going to keep falling further and further behind.\n\n(NOTE - the old indices may appear on this tab for up to 24 hours after an index is changed)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{consumer_group=~\".*ingestor.*\", kubernetes_namespace=\"$namespace\"})by(consumer_group)",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  },
  {
   "title": "Event Ingestion / second",
   "type": "timeseries",
   "description": "The rate per second of all event ingestion by Azul",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(azul_ingest_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (type, status)",
     "legendFormat": "{{type}}: {{status}}"
    }
   ]
  },
  {
   "title": "Binary Event Ingestion Statuses",
   "type": "piechart",
   "description": "Total ingestion of binary type events by Azul",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"binary\",kubernetes_namespace=\"$namespace\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Plugin Event Ingestion Statuses",
   "type": "piechart",
   "description": "Total ingestion of plugin type events by Azul",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"plugin\",kubernetes_namespace=\"$namespace\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Event Ingestion Statuses",
   "type": "piechart",
   "description": "Total ingestion of status type events by Azul",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"status\",kubernetes_namespace=\"$namespace\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Download Status Event Ingestion",
   "type": "piechart",
   "description": "Total ingestion of download status type events by Azul",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"download\",kubernetes_namespace=\"$namespace\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Event Ingestion Failures / interval",
   "type": "timeseries",
   "description": "Total ingestion with status != success",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(azul_ingest_total{status!=\"success\",kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (type, status, plugin)",
     "legendFormat": "{{type}} {{plugin}} {{status}}"
    }
   ]
  },
  {
   "title": "Binary Event Ingestion",
   "type": "piechart",
   "description": "Total ingestion of binary type events by Azul",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"binary\",kubernetes_namespace=\"$namespace\"}) by (status,plugin)",
     "legendFormat": "{{plugin}}: {{status}}"
    }
   ]
  },
  {
   "title": "Plugin Event Ingestion",
   "type": "piechart",
   "description": "Total ingestion of plugin type events by Azul",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"plugin\",kubernetes_namespace=\"$namespace\"}) by (status,plugin)",
     "legendFormat": "{{plugin}}: {{status}}"
    }
   ]
  },
  {
   "title": "Status Event Ingestion",
   "type": "piechart",
   "description": "Total ingestion of status type events by Azul",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"status\",kubernetes_namespace=\"$namespace\"}) by (status,plugin)",
     "legendFormat": "{{plugin}}: {{status}}"
    }
   ]
  },
  {
   "title": "Download Status Event Ingestion",
   "type": "piechart",
   "description": "Total ingestion of download status type events by Azul",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_ingest_total{type=\"download\",kubernetes_namespace=\"$namespace\"}) by (status,plugin)",
     "legendFormat": "{{plugin}}: {{status}}"
    }
   ]
  },
  {
   "title": "Binary Feature Encoding Error rate",
   "type": "timeseries",
   "description": "Show the rate at which errors are occurring over time for different plugins results during encoding of feature values.\nThis results in some feature values being omitted from the Opensearch database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate({app=~\"ms-ingest-.*-error\", namespace=\"$namespace\", filename=\"/logs/ingest-error.log\"} | json error_type=\"error_type\", author=\"author\", error=\"error\" | error_type = `feature_encoding` [$__auto])",
     "legendFormat": "{{author}}-ERROR:{{error}}"
    }
   ]
  },
  {
   "title": "Last 100 Ingest Errors",
   "type": "logs",
   "description": "Shows the last 100 ingest errors for any of the ingestors, if you want to select a specific ingestor change the error_log_ingestor up the top.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=~\"ms-ingest-.*-error\", namespace=\"$namespace\", app=\"ms-ingest-binary-ingest-error\"}",
     "legendFormat": "{{app}}",
     "maxLines": 100
    }
   ]
  }
 ]
}