{
 "title": "Restapi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "top_api_paths",
    "query": {
     "query": "query_result(topk(10, sum(rate(azulapi_requests_total{path=~\"^/api/.*\"}[$__range])) by (path)))"
    }
   },
   {
    "name": "top_api_errors",
    "query": {
     "query": "query_result(topk(10, sum(rate(azulapi_requests_total{path=~\"^/api/.*\", status_code=~\"^5..$\"}[$__range])) by (path)))"
    }
   },
   {
    "name": "slowest_api_paths",
    "query": {
     "query": "query_result( topk( 10, ( sum by (path) (rate(azulapi_request_duration_seconds_sum{path=~\"^/api/.*\"}[$__range])) / sum by (path) (rate(azulapi_request_duration_seconds_count{path=~\"^/api/.*\"}[$__range])) ) ))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Restapi\nThis dashboard displays various statistic regarding the restapi performance:<br><br>"
   }
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "description": "Application performance index: calculated based on the response times of requests. The closer to 1 this number is the better",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum(rate(azulapi_request_duration_seconds_bucket{le=\"5.0\", status_code=~\"^(2..|404)$\", path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))\n+\nsum(rate(azulapi_request_duration_seconds_bucket{le=\"7.5\", status_code=~\"^(2..|404)$\", path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))\n) / 2 / sum(rate(azulapi_request_duration_seconds_count{path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "description": "The total number of status code types returned by api calls",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(azulapi_requests_total{path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Endpoint Responsiveness",
   "type": "table",
   "description": "Total number of requests for each endpoint",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(azulapi_requests_total{kubernetes_namespace=\"$namespace\"}[$__range])) by (method, path)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(azulapi_request_duration_seconds_bucket{kubernetes_namespace=\"$namespace\"}[$__range])) by (le, method, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(azulapi_request_duration_seconds_bucket{kubernetes_namespace=\"$namespace\"}[$__range])) by (le, method, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.999, sum(rate(azulapi_request_duration_seconds_bucket{kubernetes_namespace=\"$namespace\"}[$__range])) by (le, method, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Number of api requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(azulapi_requests_total{path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(azulapi_requests_total{path=~\"^/api/.*\", status_code=~\"^2..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Success (2xx)"
    },
    {
     "expr": "sum(irate(azulapi_requests_total{path=~\"^/api/.*\", status_code=~\"^5..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Server Error (5xx)"
    },
    {
     "expr": "sum(irate(azulapi_requests_total{path=~\"^/api/.*\", status_code=~\"^4..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Client Error (4xx)"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "heatmap",
   "description": "Request latency. The time it takes for an api call to complete",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(azulapi_request_duration_seconds_bucket{path=~\"^/api/.*\", kubernetes_namespace=\"$namespace\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "bargauge",
   "description": "Request latency. The time it takes for an api call to complete",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(azulapi_request_duration_seconds_bucket{path=~\"/api/.*\", kubernetes_namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top 5XX Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(azulapi_requests_total{status_code=~\"^5..$\", kubernetes_namespace=\"$namespace\"}[$__range])) by (path, method, status_code)"
    }
   ]
  },
  {
   "title": "RestAPI Audit Errors",
   "type": "stat",
   "description": "Number of audit errors (logged errors)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"restapi-server-audit\"} |~ `(?i)status=5\\d\\d | (?i)status=422` [$__range])"
    }
   ]
  },
  {
   "title": "Audit Errors over time",
   "type": "timeseries",
   "description": "Number of audit errors (logged errors)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate({app=\"restapi-server-audit\"} |~ `(?i)status=5\\d\\d | (?i)status=422` [$__interval])"
    }
   ]
  }
 ]
}