{
 "title": "Caching",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "ContentIncludeMetastore",
    "label": "Content Cache include Metastore",
    "query": "yes : .*, no : plugin"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dispatcher Cache Overview\r\nThis dashboard is primarily concerned with cache metrics.<br><br>"
   }
  },
  { "title": "Replay Plugin Completion Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "This cache replays long running plugins on newly received events.\r\nThis can save processing when the same binary is seen multiple times over a longer period of time."
   }
  },
  {
   "title": "Total Cache Hits (rolling 1 hour window)",
   "type": "timeseries",
   "description": "Total number of cache hits",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_replay_cache_hit_count{kubernetes_namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Cache Hits by Plugin (rolling 1 hour window)",
   "type": "timeseries",
   "description": "Number of cache hits per plugin",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_replay_cache_hit_count{kubernetes_namespace=\"$namespace\", }[1h])) by (name, version)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Profit (rolling 1 hour window)",
   "type": "timeseries",
   "description": "Benefits Subtracting Costs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_replay_cache_hit_seconds{kubernetes_namespace=\"$namespace\"}[1h])) - (sum(increase(dispatcher_events_produce_pipelines_duration_sum{kubernetes_namespace=\"$namespace\",pipeline=\"ReplayPluginCompletion\"}[1h]) + increase(dispatcher_events_consume_pipelines_duration_sum{kubernetes_namespace=\"$namespace\",pipeline=\"ReplayPluginCompletion\"}[1h])))",
     "legendFormat": "Profit"
    }
   ]
  },
  {
   "title": "Cache Costs (rolling 1 hour window)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_events_produce_pipelines_duration_sum{kubernetes_namespace=\"$namespace\",pipeline=\"ReplayPluginCompletion\"}[1h])) by (pipeline)",
     "legendFormat": "Produce"
    },
    {
     "expr": "sum(increase(dispatcher_events_consume_pipelines_duration_sum{kubernetes_namespace=\"$namespace\",pipeline=\"ReplayPluginCompletion\"}[1h])) by (pipeline)",
     "legendFormat": "Consume"
    }
   ]
  },
  {
   "title": "Cache Benefit (rolling 1 hour window)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_replay_cache_hit_seconds{kubernetes_namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Dedupe Cache (prevent a plugin taking the same job twice)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "dedupe hit rate - for dp events",
   "type": "stat",
   "description": "Number of events that were deduplicated, preventing a plugin from running twice.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dispatcher_dedupe_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}) by (app)/sum(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}) by (app)",
     "legendFormat": "{{ app}}"
    }
   ]
  },
  {
   "title": "Dedupe hit, miss and collisions per interval",
   "type": "timeseries",
   "description": "Total number of dedupe events per interval. (Log scale for readability.)",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}[$__rate_interval])) by (app) - sum(increase(dispatcher_dedupe_hits_total{kubernetes_namespace=\"$namespace\", name=~\"dp-.*-events\"}[$__rate_interval])) by (app) - sum(increase(dispatcher_dedupe_collisions_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}[$__rate_interval])) by (app)",
     "legendFormat": "misses - {{ app}}"
    },
    {
     "expr": "sum(increase(dispatcher_dedupe_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}[$__rate_interval])) by (app) ",
     "legendFormat": "hits - {{ app }}"
    },
    {
     "expr": "sum(increase(dispatcher_dedupe_collisions_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}[$__rate_interval])) by (app) ",
     "legendFormat": "collisions - {{ app}}"
    }
   ]
  },
  {
   "title": "dedupe collision rate - for dp events",
   "type": "stat",
   "description": "Number of collisions that occur when inserting data into the dedupe cache.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dispatcher_dedupe_collisions_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}) by (app)/sum(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-events\"}) by (app)",
     "legendFormat": "{{ app}}"
    }
   ]
  },
  {
   "title": "dedupe hit rate for streams - Shouldn't have any.",
   "type": "stat",
   "description": "Dedupe hit rate for streams - this should always be disabled",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dispatcher_dedupe_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-streams\"}) by (app)/sum(dispatcher_dedupe_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*-streams\"}) by (app)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Storage Cache (a.k.a Content Cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Content Cache hit Rate",
   "type": "stat",
   "description": "Cache hit percentage\nhits/total_lookups",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dispatcher_data_cache_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-$ContentIncludeMetastore-streams\"}) by (app)/sum(dispatcher_data_cache_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-$ContentIncludeMetastore-streams\"}) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Content Cache hit and miss per interval",
   "type": "timeseries",
   "description": "The number of hits and misses per interval for the content cache.\ne.g the number of files that were cached and returned in a request instead of having to re-query S3.",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "increase(dispatcher_data_cache_lookups_total{kubernetes_namespace=\"$namespace\", app=~\"dp-$ContentIncludeMetastore-streams\"}[$__rate_interval]) - increase(dispatcher_data_cache_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-$ContentIncludeMetastore-streams\"}[$__rate_interval])",
     "legendFormat": "misses - {{ app}}"
    },
    {
     "expr": "increase(dispatcher_data_cache_hits_total{kubernetes_namespace=\"$namespace\", app=~\"dp-$ContentIncludeMetastore-streams\"}[$__rate_interval])",
     "legendFormat": "hits - {{ app }}"
    }
   ]
  }
 ]
}