{
 "title": "Filestore Throughput",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "dispatcher",
    "query": {
     "query": "label_values(dispatcher_restapi_time_seconds_count,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dispatcher - Filestore Throughput\r\nThis dashboard displays data based on dispatcher file-store requests <br><br>"
   }
  },
  { "title": "$dispatcher-API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "dispatcher" },
  {
   "title": "Requests per file-store operation.",
   "type": "timeseries",
   "description": "The requests per second for the listed file-store operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(app, method) (rate(dispatcher_streams_op_duration_count{app=\"$dispatcher\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Cumulative operation time",
   "type": "timeseries",
   "description": "Total time an operation is taking over an interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_streams_op_duration_sum{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\"}[$__rate_interval])) by (le, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Average operation time",
   "type": "timeseries",
   "description": "Average operation time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(app, method) (avg_over_time(dispatcher_streams_op_duration_sum{kubernetes_namespace=\"$namespace\", app=\"$dispatcher\"}[$__interval])) / sum by(app, method) (avg_over_time(dispatcher_streams_op_duration_count{app=\"$dispatcher\", kubernetes_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "p99 request duration",
   "type": "heatmap",
   "description": "the 99th percentile for completing a request by method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(dispatcher_streams_op_duration_bucket{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\", result=\"ok\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "p50 request duration",
   "type": "heatmap",
   "description": "the 50th percentile for completing a request by method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(dispatcher_streams_op_duration_bucket{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\", result=\"ok\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}