{
 "title": "File Identification",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dispatcher - File Identification\nThis dashboard displays failed dispatcher file identification by magic and mime<br><br>"
   }
  },
  {
   "title": "Type Identification Failures (Shortened magic)",
   "type": "bargauge",
   "description": "Shortened magic type miss identification.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum (label_replace(dispatcher_identify_fail{kubernetes_namespace=\"$namespace\", magic!=\"data\"}, \"magic_short\", \"$1\", \"magic\", \"(.{20}).*\")) by (magic_short))",
     "legendFormat": "{{magic_short}}"
    }
   ]
  },
  {
   "title": "Type Identification Failures (mime)",
   "type": "bargauge",
   "description": "Unmatched files with there mime type only",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum (dispatcher_identify_fail{kubernetes_namespace=\"$namespace\", magic!=\"data\"}) by (mime))",
     "legendFormat": "{{mime}} | {{magic}}"
    }
   ]
  },
  {
   "title": "Type Identification Failures (mime | magic)",
   "type": "bargauge",
   "description": "Unmatched files with their mime and magic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum (dispatcher_identify_fail{kubernetes_namespace=\"$namespace\", magic!=\"data\"}) by (mime, magic))",
     "legendFormat": "{{mime}} | {{magic}}"
    }
   ]
  },
  { "title": "Data Download summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total downloaded Bytes",
   "type": "timeseries",
   "description": "The total data downloaded by dispatcher",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dispatcher_data_downloaded_bytes_total{app=~\"dp-.*\", kubernetes_namespace=\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total uploaded Bytes",
   "type": "timeseries",
   "description": "The total data uploaded by dispatcher",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dispatcher_data_uploaded_bytes_total{app=~\"dp-.*\", kubernetes_namespace=\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Data Downloaded Rate",
   "type": "timeseries",
   "description": "The dispatcher download rate",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_data_downloaded_bytes_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*\"}[5m])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Data Uploaded Rate",
   "type": "timeseries",
   "description": "The dispatcher upload rate",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_data_uploaded_bytes_total{kubernetes_namespace=\"$namespace\", app=~\"dp-.*\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}