{
 "title": "Memory",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "dispatcher",
    "query": {
     "query": "label_values(go_goroutines,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dispatcher Memory Debugging\nThis dashboard displays overall memory used by Dispatcher and Kafka<br><br>"
   }
  },
  {
   "title": "RSS",
   "type": "stat",
   "description": "Current process resident memory used by Dispatcher instances in Kubernetes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"$dispatcher\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}} {{instance}}"
    }
   ]
  },
  {
   "title": "Go Heap Alloc",
   "type": "stat",
   "description": "Go heap allocation for Dispatcher instances in Kubernetes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app}} {{instance}}"
    }
   ]
  },
  {
   "title": "Mem Diff Other CGO?",
   "type": "stat",
   "description": "CGO Usage, Swapped pages if negative, etc.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app, instance) (process_resident_memory_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"}) -  sum by (app,instance) (go_memstats_sys_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{app}} {{instance}}"
    }
   ]
  },
  {
   "title": "Dispatcher Memory",
   "type": "timeseries",
   "description": "Total memory used by Dispatcher instances in Kubernetes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (app, instance) (go_memstats_sys_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Go Memory {{app}}-{{instance}}"
    },
    {
     "expr": "sum by (app, instance) (process_resident_memory_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "RSS {{app}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Go GC Collection p/s",
   "type": "timeseries",
   "description": "Go Garbage collection rate per second by Dispatcher instances in Kubernetes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_count{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (app,instance)",
     "legendFormat": "Rate {{app}}-{{instance}}"
    },
    {
     "expr": "sum(go_memstats_gc_cpu_fraction{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"}) by (app,instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routine Count",
   "type": "timeseries",
   "description": "Number of go routines running on each instance of dispatcher",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (app, instance) (go_goroutines{app=~\"$dispatcher\", kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{app}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Golang Mem Breakdown",
   "type": "timeseries",
   "description": "Go memory breakdown showing in-use stack and heap memory, idle heap memory and Go GC memory use",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (go_memstats_stack_inuse_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Go Stack In Use {{instance}}"
    },
    {
     "expr": "sum by (app, instance) (go_memstats_heap_inuse_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Go Heap In Use {{app}}-{{instance}}"
    },
    {
     "expr": "sum by (app, instance) (go_memstats_heap_idle_bytes{app=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Go Heap Idle (reusable) {{app}}-{{instance}}"
    },
    {
     "expr": "sum by (app, instance) (go_memstats_gc_sys_bytes{name=~\"$dispatcher\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Go GC System Use {{app}}-{{instance}}"
    }
   ]
  }
 ]
}