{
 "title": "Dispatcher Restapi Activity",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "dispatcher",
    "query": {
     "query": "label_values(dispatcher_restapi_time_seconds_count,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dispatcher - API Summary\r\nThis dashboard displays data based on dispatcher endpoint requests <br><br>"
   }
  },
  { "title": "$dispatcher-API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "dispatcher" },
  {
   "title": "Requests per API endpoint.",
   "type": "timeseries",
   "description": "The requests per second for the listed API endpoint/method pairs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(app, path, method) (rate(dispatcher_restapi_time_seconds_count{app=\"$dispatcher\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Cumulative request time",
   "type": "timeseries",
   "description": "Total time a request is taking over an interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(dispatcher_restapi_time_seconds_sum{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\"}[$__rate_interval])) by (le, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "p50 request time",
   "type": "heatmap",
   "description": "the 50th percentile for completing a request by path.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(dispatcher_restapi_time_seconds_bucket{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\"}[$__rate_interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "p99 request time",
   "type": "heatmap",
   "description": "the 99th percentile for completing a request by path.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(dispatcher_restapi_time_seconds_bucket{kubernetes_namespace=\"$namespace\",app=\"$dispatcher\"}[$__rate_interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Restapi Activity by User Agent",
   "type": "timeseries",
   "description": "Shows activity on restapi for each seen user agent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate({component=\"dispatcher\", category=\"restapi\", namespace=\"$namespace\", app=\"$dispatcher\"} | json user_agent=\"user_agent\" | __error__=`` [$__auto])",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Restapi Errors by User Agent",
   "type": "timeseries",
   "description": "Shows http errors caused by user agents. Excludes 404s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate({component=\"dispatcher\", app=\"$dispatcher\", category=\"restapi\", subset=\"err\", namespace=\"$namespace\"} | json status=\"status\", route=\"route\", method=\"method\", user_agent=\"user_agent\" | status != `404` | __error__=`` [$__auto])",
     "legendFormat": "{{user_agent}} - {{method}} {{route}} - {{status}}"
    }
   ]
  },
  {
   "title": "Restapi 4xx Client Errors",
   "type": "logs",
   "description": "Restapi errors likely caused by client issues. Excludes 404s as they are expected for many endpoints.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{component=\"dispatcher\", app=\"$dispatcher\", category=\"restapi\", subset=\"err\", namespace=\"$namespace\"} | json user_agent=\"user_agent\", status=\"status\" | status < 500 | status != `404` | __error__=``",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Restapi 5xx Server Errors",
   "type": "logs",
   "description": "Restapi errors likely caused by server issues.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "{component=\"dispatcher\", app=\"$dispatcher\", category=\"restapi\", subset=\"err\", namespace=\"$namespace\"} | json | status >= 500 | __error__=``",
     "maxLines": 1000
    }
   ]
  }
 ]
}