{
 "title": "Assemblyline Receiver",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(azul_plugin_assemblyline_requests_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Assemblyline Receiver\n\nThis dashboard tracks Assemblyline Receiver and tracks\nerrors such as bad classification mappings or bad requests \nfrom Assemblyline to the plugin.\n"
   }
  },
  {
   "title": "Classification Errors",
   "type": "stat",
   "description": "Number of submissions dropped because the Assemblyline classification couldn't be mapped to an azul classification.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(classification) (azul_plugin_assemblyline_dropped_classifications_total{kubernetes_namespace=\"$namespace\"}) > 0",
     "legendFormat": "{{classification}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "description": "The total number of status code types returned by api calls",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(azul_plugin_assemblyline_requests_total{path!=\"/metrics\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Number of api requests per second",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(azul_plugin_assemblyline_requests_total{path!=\"/metrics\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(azul_plugin_assemblyline_requests_total{path!=\"/metrics\", status_code=~\"^2..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Success (2xx)"
    },
    {
     "expr": "sum(irate(azulapi_requests_total{path!=\"/metrics\", status_code=~\"^5..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Server Error (5xx)"
    },
    {
     "expr": "sum(irate(azulapi_requests_total{path!=\"/metrics\", status_code=~\"^4..$\", kubernetes_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Client Error (4xx)"
    }
   ]
  }
 ]
}