{
 "title": "Bad Plugins",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   },
   {
    "name": "plugins_that_produce_events",
    "query": {
     "query": "label_values(dispatcher_events_status_published,plugin)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard summarises plugins that potentially have issues.\n\nIt is likely most of the plugins listed here are fine, but this allows users to determine the plugins that have the slowest performance."
   }
  },
  {
   "title": "Error Probability Summary",
   "type": "stat",
   "description": "Likelihood that a random relevant event will raise an error. errors / (errors + successes)",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(dispatcher_events_status_published{status=~\"error-.*\", kubernetes_namespace=\"$namespace\"}[$__range])) by (plugin) / sum(increase(dispatcher_events_status_published{status=~\"completed.*|error-.*\", kubernetes_namespace=\"$namespace\"}[$__range])) by (plugin)) > 0.3",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Plugins that have never Produce Events",
   "type": "table",
   "description": "NOTE - only works when plugins_that_produce_events and plugins_that_produce_no_events are set to ALL.\nPlugins that never produce events (never opt-out, complete or error)\nThese plugins have all their events filtered out by dispatcher.\nThis may mean their filters are too specific but does mean no file matching the filter has entered the system.",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "group(dispatcher_events_filtered_total{kubernetes_namespace=\"$namespace\", plugin!~\"$plugins_that_produce_events|ingestor.*|bk-.*\"}) by (plugin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Summary - Slow plugin ID",
   "type": "stat",
   "description": "90% of events are processed in the indicated time.\nThis is a summary view to allow the identification of slow plugin.",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, publisher) (rate(dispatcher_processing_time_seconds_bucket{kubernetes_namespace=\"$namespace\"}[5m]))) > 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plugins that opt-out 100% of the time",
   "type": "table",
   "description": "List of plugins that have opted out 100% of the time over the selected time range.",
   "gridPos": { "h": 25, "w": 3, "x": 21, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(dispatcher_events_status_published{kubernetes_namespace=\"$namespace\", status=\"opt-out\"}[$__rate_interval])) by (plugin) / sum(rate(dispatcher_events_status_published{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (plugin)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live/Expedite Lags - Lagging plugins",
   "type": "stat",
   "description": "Highlight the plugins with the largest live lag.\nThis indicates plugins that are likely misconfigured or not working as expected.\n\nNote: the number is the current average so not useful for comparison with the per plugin value.",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(consumer_group) (burrow_kafka_consumer_lag_total{kubernetes_namespace=\"$namespace\", consumer_group=~\".*-live|expedite\", consumer_group!~\".*-ingestor-.*\"})) > 5000",
     "legendFormat": "{{consumer_group}}"
    }
   ]
  }
 ]
}