{
 "title": "Report Feeds",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "publisher",
    "query": {
     "query": "label_values(publisher_duration{job=\"$jobName\"},publisher)"
    }
   },
   {
    "name": "jobName",
    "query": {
     "query": "label_values(total_runtime{job=~\"ReportFeeds.*\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Stats will only update once every 4 hours."
   }
  },
  {
   "title": "Total Runtime",
   "type": "table",
   "description": "Total runtime for report feeds to scrape all reports.",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "total_runtime{job=\"$jobName\"}",
     "legendFormat": "Run Time"
    }
   ]
  },
  {
   "title": "Last Runtime Share",
   "type": "piechart",
   "description": "Total share of Runtime by each publisher for the last run of report feed.",
   "gridPos": { "h": 21, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(publisher_duration{job=\"$jobName\"}) by (publisher)",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Publishers Completing",
   "type": "state-timeline",
   "description": "Publishers that are successfully grabbing all of their data without a failure.",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "publisher_succeeded_total{job=\"$jobName\"}",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  { "title": "Debug Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Failing due to Fetch",
   "type": "piechart",
   "description": "Report feeds that are failing to fetch any data.\nThis is typically due to redirects or the report feed having been removed.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(publisher) (publisher_failures_total{job=\"$jobName\", reason=\"fetch\"}) != 0",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Failing due to Process",
   "type": "piechart",
   "description": "Report feeds that are failing to be processed.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(publisher) (publisher_failures_total{job=\"$jobName\", reason=\"process\"}) != 0",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Quick summary of which publishers",
   "type": "stat",
   "description": "Quick summary of which report publishers are working based on which ones of them are getting results.\nSo even if they aren't failing they might not ever get useful data.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(publisher_events_generated_total{job=\"$jobName\"}) by (publisher)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  { "title": "$publisher Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "repeat": "publisher" },
  {
   "title": "Publisher Reports Read",
   "type": "stat",
   "description": "Total reports read by a publisher.",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(publisher_reports_read_total{job=\"$jobName\", publisher=\"$publisher\"})",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "description": "Total failures by a publisher for the two reasons possible \n- fetch: Couldn't download data from the publisher.\n - process: When data was acquired from the publisher but couldn't be converted to events and forwarded to dispatcher.",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(publisher_failures_total{job=\"$jobName\",publisher=\"$publisher\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Total Runtime",
   "type": "table",
   "description": "Total runtime for this report feed while scraping, processing and generating events from reports.",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "publisher_duration{job=\"$jobName\", publisher=\"$publisher\"}",
     "legendFormat": "Run Time"
    }
   ]
  },
  {
   "title": "Publisher Events generated by type",
   "type": "stat",
   "description": "Total number of events and the type of events a publisher has generated.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(publisher_events_generated_total{job=\"$jobName\", publisher=\"$publisher\"}) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Reports Attached",
   "type": "table",
   "description": "Hashes that reports have been attached to.",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(sha256) (publisher_events_generated_total{job=\"$jobName\", event_type=\"attach_report\", publisher=\"$publisher\"})",
     "legendFormat": "{{sha256}}"
    }
   ]
  },
  {
   "title": "Publisher Events generated by type",
   "type": "timeseries",
   "description": "Total number of events and the type of events a publisher has generated.",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(publisher_events_generated_total{job=\"$jobName\", publisher=\"$publisher\"}) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Failure Reasons",
   "type": "table",
   "description": "List the exception associated with failures, the reason for failures can be: \n- fetch: Couldn't download data from the publisher.\n - process: When data was acquired from the publisher but couldn't be converted to events and forwarded to dispatcher.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "publisher_failures_total{job=\"$jobName\", publisher=\"$publisher\"}",
     "legendFormat": "{{message}}"
    }
   ]
  }
 ]
}