{
 "title": "Retrohunt Status",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(retrohunt_bytes_ingested_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Retrohunt\n\nThis dashboard tracks the status of the retrohunt plugin, including the state of storage, indexing and resource usage."
   }
  },
  {
   "title": "RAM usage (virtual)",
   "type": "timeseries",
   "description": "Total RAM usage by container in the retrohunt worker pod.\nNote - main is the ingestor.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"plugin-retrohunt-worker.*\", container!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage (RSS)",
   "type": "timeseries",
   "description": "Total RAM usage by container in the retrohunt worker pod.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"$namespace\", pod=~\"plugin-retrohunt-worker.*\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Indexer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Indexes Created",
     "type": "stat",
     "description": "Indexes created for the different indexes and their different types (periodic or sizebased) periodic indices constantly override themselves. Where sizebased are permanent until aged off.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 133 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_bgis_created_total{kubernetes_namespace=\"$namespace\"}) by (type, index)",
       "legendFormat": "{{type}}-{{index}}"
      }
     ]
    },
    {
     "title": "BGI disk usage",
     "type": "stat",
     "description": "Total disk used store BGI (Big Grep Index) files.\nSeparated out by index name and a total sum is included.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_indexer_bytes_in_bgi_directory{kubernetes_namespace=\"$namespace\"}) by (index)",
       "legendFormat": "index-{{index}}-size"
      }
     ]
    },
    {
     "title": "Index Splits and Deletions",
     "type": "stat",
     "description": "Total number of indices that have been split and deleted.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 133 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type, index) (retrohunt_index_fails_total{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "{{index}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingest/worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 134 }, "options": { "content": "### Ingestion - stats\n" } },
    { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 9, "y": 134 }, "options": { "content": "### Worker - stats\n" } },
    {
     "title": "Bytes Ingested",
     "type": "stat",
     "description": "Total bytes ingested by retrohunt ingestor.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_bytes_ingested_total{kubernetes_namespace=\"$namespace\"}) by (kubernetes_namespace)",
       "legendFormat": "Bytes Ingested"
      }
     ]
    },
    {
     "title": "Ingest - Cache Size",
     "type": "stat",
     "description": "Total size of the cache per index, by default when this gets above 10GiB it will reset to 0 as an index will trigger.\nNote that this behaviour may be different if a different max cache size is configured.",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_bytes_in_cache{kubernetes_namespace=\"$namespace\"}) by (indexer)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Job results",
     "type": "stat",
     "description": "Totals for the worker job results.\nWas a workers run completed or failed or cancelled.",
     "gridPos": { "h": 5, "w": 7, "x": 9, "y": 142 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_worker_jobs_run_total{kubernetes_namespace=\"$namespace\"}) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average worker runtime",
     "type": "stat",
     "description": "The average runtime for all workers.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_worker_runtime_sum{kubernetes_namespace=\"azul-dev\"}/retrohunt_worker_runtime_count{kubernetes_namespace=\"azul-dev\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Succes rate",
     "type": "stat",
     "description": "Percentage of jobs worker has succeeded.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(retrohunt_worker_jobs_run_total{kubernetes_namespace=\"$namespace\", status=\"COMPLETED\"}) / sum(retrohunt_worker_jobs_run_total{kubernetes_namespace=\"$namespace\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Request Rates",
     "type": "timeseries",
     "description": "Request rates for the Retrohunt restapi.",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "suM(irate(retrohunt_server_requests_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (method, path, status_code)",
       "legendFormat": "{{method}} {{path}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Status Codes",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(retrohunt_server_requests_total{kubernetes_namespace=\"$namespace\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  { "title": "Extra Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Broad/Narrow phase comparision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(retrohunt_broad_phase_duration_seconds_bucket[$__rate_interval])) by (le, query_hash)\r\n)",
     "legendFormat": "Broad - {{query_hash}}"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(retrohunt_narrow_phase_duration_seconds_bucket[$__rate_interval])) by (le, query_hash)\r\n)",
     "legendFormat": "Narrow - {{query_hash}}"
    }
   ]
  }
 ]
}