{
 "title": "Infra Health",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(status_status,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "# Infra Health\r\nThis dashboard displays the current health of Azul's infrastructure.\r\n\r\nIt's aim is to give a quick summary of what infrastructure is working and what infrastructure is failing to help administrators quickly rule out systems as causing system errors or performance issues."
   }
  },
  {
   "title": "Is Status Collection working",
   "type": "state-timeline",
   "description": "Check if status collection is working or not and provides a reason if it isn't",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by(reason) (status_status{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Azul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": {
    "content": "Status of opensearch's various functions:\n- docs           - Azul Docs endpoint that hosts Azul's documentation.\n- restapi        - Swagger RestAPI that can be used to test Opensearch queries against Azul.\n- restapi_config - Swagger RestAPI json definition endpoint.\n- webui          - Azul WebUI endpoint where users are expected to interact with Azul.\n- webui_static   - Query against part of Azul WebUI static content to confirm static content is hosted."
   }
  },
  {
   "title": "AzulProbe Status",
   "type": "state-timeline",
   "description": "Status of various Azul endpoints simply verifying Azul is up and running as expected.\nRed means that endpoint didn't return with a success result and there is probably something with the core Azul hosting.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"azul\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "AzulProbe Action Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how performant Azul is.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"azul\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Opensearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "options": {
    "content": "Status of opensearch's various functions:\n- auth         - can the opensearch writer user login.\n- create_index - can the user create an index. (depends on Auth)\n- index_docs   - can a document be index into the created index. (depends on create_index)\n- get_docs     - can the user search for documents in the index. (depends on index_docs)\n- get_docs_agg - can the user use an aggregation search in the index. (depends on index_docs)\n"
   }
  },
  {
   "title": "Opensearch Status",
   "type": "state-timeline",
   "description": "Status of various actions opensearch is expected to do.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"opensearch\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Opensearch Action Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how much load Opensearch is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"opensearch\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "options": {
    "content": "Status of kafka's various functions:\n- connect       - can the kafka broker be contacted.\n- create_topic  - can the test topic be created. (depends on connect)\n- produce_topic - can data be produced into the test kafka topic (depends on create_topic)\n- consume_topic - can data be consumed from test kafka topic (depends on produce_topic)\n\n"
   }
  },
  {
   "title": "Kafka Status",
   "type": "state-timeline",
   "description": "Status of various actions kafka is expected to do.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"kafka\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Kafka Action Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how much load Kafka is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"kafka\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 23 },
   "options": {
    "content": "Status of storage's various functions:\n- auth          - can storage be contacted and logged into.\n- parent_exists - does the parent container/bucket exist. (depends on auth)\n- blob_upload   - can data be uploaded to the container (depends on parent_exists)\n- blob_download - can data be downloaded from the container (depends on blob_upload)\n\n"
   }
  },
  {
   "title": "Storage Status",
   "type": "state-timeline",
   "description": "Status of various actions storage is expected to do.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"storage\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "StorageAction Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how much load storage is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"storage\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Backup Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 29 },
   "options": {
    "content": "Status of backup storage's various functions:\n- auth          - can storage be contacted and logged into.\n- parent_exists - does the parent container/bucket exist. (depends on auth)\n- blob_upload   - can data be uploaded to the container (depends on parent_exists)\n- blob_download - can data be downloaded from the container (depends on blob_upload)\n\n"
   }
  },
  {
   "title": "Backup Storage Status",
   "type": "state-timeline",
   "description": "Status of various actions backup storage is expected to do.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 29 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"backup\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Backup Storage Action Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how much load  backup storage is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"backup\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 35 },
   "options": {
    "content": "Status of redis's various functions:\n- auth - can redis be contacted and logged into.\n- set  - can a key value pair be set in redis. (depends on auth)\n- get  - can a key's value be found in redis. (depends on set)\n\n"
   }
  },
  {
   "title": "Redis Status",
   "type": "state-timeline",
   "description": "Status of various actions redis caching is expected to do.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 35 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"redis\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Redis Action Duration",
   "type": "stat",
   "description": "How long different actions take.\nIndicates how much load redis is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"redis\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 41 },
   "options": {
    "content": "Status of Auth getting a valid token:\n- get_token - can a token be acquired using a service account.\n- valid_token - Does a token have a valid audience and roles. (depends on get_token)\n\n"
   }
  },
  {
   "title": "Auth Status",
   "type": "state-timeline",
   "description": "Status of auth, first getting a token and then validating it is correct.\nRed means the action could not be performed and green means the action could be performed.",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "sum by(action) (azul_health_check_status{kubernetes_namespace=\"$namespace\", system=\"auth\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Auth Action Duration",
   "type": "stat",
   "description": "How long different actions take. (get_token queries the auth server and valid_token is run on the stats pod so should always be super fast)\nIndicates how much load auth is under.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(azul_health_check_timing{kubernetes_namespace=\"$namespace\", system=\"auth\"}) by (action)",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}