{
 "title": "Audit Logs Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "usernameRegex" },
   { "name": "filterTextOrSha256", "label": "filterTextOrSha256" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays audit logging for a specific user and their requests to the platform.<br>\nIt has a filter to allow targeted auditing of sha256's a user has viewed or filter for arbitrary data like methods or specific paths."
   }
  },
  {
   "title": "Users who appear on filtered log lines",
   "type": "table",
   "description": "Users who appear on lines that contain the specified filter text specified by the variable filterTextOrSha256. Not affected by usernameRegex",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} |~ `(?i)$filterTextOrSha256` | logfmt | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Requests per user",
   "type": "timeseries",
   "description": "Total number of requests a user has made to the API in the given time window.",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} != `special_method` |~ `(?i)$filterTextOrSha256` | logfmt | username =~ `$usernameRegex` | __error__=`` [$__auto]))",
     "legendFormat": "{{username}}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Filtered Raw Logs",
   "type": "logs",
   "description": "The raw API logs filtered by the variables provided.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"restapi-server-audit\", namespace=\"$namespace\"} |~ `(?i)$filterTextOrSha256` | logfmt | username =~ `$usernameRegex`"
    }
   ]
  }
 ]
}