{
 "title": "Audit Requests By User Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "usernameRegex" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays audit logging for restapi and can be filtered down to a user or group of users by regex.<br>\n"
   }
  },
  {
   "title": "Total Requests by user",
   "type": "piechart",
   "description": "Total number of requests user(s) have made to the Azul API in the current time window.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} != `special_method` | logfmt | username =~ `$usernameRegex` | username != `-` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Purge Operations by users",
   "type": "piechart",
   "description": "Number of purge operations performed by users filtered by userRegex.",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} |~ `(?i)/v0/purge` | logfmt | username != `-` | username =~ `$usernameRegex` | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Upload Requests by User",
   "type": "piechart",
   "description": "Number of uploads performed by user(s) to Azul.",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} | logfmt | special_method = `POST` | special_path =~ `.*/v0/binaries/source|.*/v0/binaries/source/dataless` | username =~ `$usernameRegex` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Insert Requests By User",
   "type": "piechart",
   "description": "Number of inserts performed by user(s) to Azul. (child binary uploads)",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} | logfmt | special_method = `POST` | special_path =~ `.*/v0/binaries/child|.*/v0/binaries/child/dataless` | username =~ `$usernameRegex` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Download Requests By User",
   "type": "piechart",
   "description": "Number of downloads performed by user(s) to Azul.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$SoloDownload+$BulkDownload", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "math" }
   ]
  },
  {
   "title": "Requests per user",
   "type": "timeseries",
   "description": "Total number of requests a user has made to the API in the given time window.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} != `special_method` | logfmt | username =~ `$usernameRegex` | __error__=`` [$__auto]))",
     "legendFormat": "{{username}}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "User RestAPI Requests",
   "type": "table",
   "description": "All requests made by a user including the method, path resultant status.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(username, generic_path, status, method) (count_over_time({app=\"restapi-server-audit\", namespace=\"$namespace\"} != `special_method` | logfmt | username =~ `$usernameRegex` | __error__=`` [$__range]))"
    }
   ]
  }
 ]
}