{
 "title": "Backup",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(burrow_kafka_consumer_lag_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Azul-Backup\n\nThis dashboard is useful for checking the status of the azul-backup service.\n\nThis dashboard displays \n* Errors when backing up specific events or objects.\n* the number of events that azul-backup is lagging by in Kafka. \n* Number of events and streams that are have been backed up.\n\n\n"
   }
  },
  {
   "title": "Azul Events and Streams Backed Up",
   "type": "timeseries",
   "description": "Number of events and streams successfully backed up during the current run of the backup server.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(recovery_backup_stats{kubernetes_namespace=\"$namespace\", stat=~\".*ok.*\"}) by (source, stat) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Azul Events and Streams Backup Issues",
   "type": "timeseries",
   "description": "Number of events and streams that have failed to backup correctly for some reason.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(source, stat) (recovery_backup_stats{kubernetes_namespace=\"$namespace\", stat!~\".*ok.*\"}) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Backup Caught Up",
   "type": "stat",
   "description": "Track if all the backup topics have caught up.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(burrow_kafka_consumer_lag_total{kubernetes_namespace=\"$namespace\", consumer_group=~\".*azul-backup-.*\"}), 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Azul-backup Consumer Lag",
   "type": "timeseries",
   "description": "Number of events that azul-backup is lagging by in kafka.\nThis is useful for checking the status of azul-backup.",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(burrow_kafka_consumer_lag_total{kubernetes_namespace=\"$namespace\", consumer_group=~\".*azul-backup-.*\"}) by (consumer_group)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Backup Caught Up",
   "type": "table",
   "description": "Track when a backup topic has completed its backup operation.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "clamp_max(sum by(consumer_group) (burrow_kafka_consumer_lag_total{kubernetes_namespace=\"$namespace\", consumer_group=~\".*azul-backup-.*\"}), 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Event Issues",
   "type": "timeseries",
   "description": "Events may be corrupted or invalid in some way during the backup process. This graph reports those failures that don't cause the whole backup to abort.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(keyword, source, event) (recovery_backup_events_error{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{keyword}} ({{source}}-{{event}})"
    }
   ]
  },
  {
   "title": "Backup Object Issues",
   "type": "timeseries",
   "description": "An issue may occur when backing up specific objects to s3. This graph reports these failures that don't cause the whole backup to abort.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum (recovery_backup_object_error{kubernetes_namespace=\"$namespace\"}) by (keyword)",
     "legendFormat": "{{keyword}}"
    }
   ]
  }
 ]
}