{
 "title": "Restore",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(burrow_kafka_consumer_lag_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Azul-Restore\n\nThis dashboard is useful for checking the status of the azul-restore service. <br/>\nNote that during a restore all streams are restored and then all events are restored. This is to prevent events being fed into the system without their files being available yet.\n\nDisplays:\n* Number of events and streams restored so far.\n* Number of errors during the restore.\n* If all streams and all events have been restored.\n\n"
   }
  },
  {
   "title": "All Streams Restored",
   "type": "stat",
   "description": "Track is all streams have been restored",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(recovery_stream_restore_complete{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Azul Streams Restored",
   "type": "timeseries",
   "description": "Number of streams successfully restored during the current run of the restore server.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 11, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "sum(recovery_restore_stats{kubernetes_namespace=\"$namespace\", stat=~\".*ok.*\", stat!~\".*events.*\"}) by (source, stat) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Azul Streams Restored Issues",
   "type": "timeseries",
   "description": "Number of streams that have failed to be restored correctly for some reason.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum by(source, stat) (recovery_restore_stats{kubernetes_namespace=\"$namespace\", stat!~\".*ok.*|.*events.*\"}) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Streams Restored",
   "type": "table",
   "description": "Tracks individual stream sources have completely been restored.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(recovery_stream_restore_complete{kubernetes_namespace=\"$namespace\"}) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "All Events Restored",
   "type": "stat",
   "description": "Tracks whether all events have been restored or not.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum(recovery_total_event_types_for_source{kubernetes_namespace=\"$namespace\"})-sum(recovery_completed_event_types_for_source{kubernetes_namespace=\"$namespace\"}), 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Azul Events Restored",
   "type": "timeseries",
   "description": "Number of streams successfully restored during the current run of the restore server.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 11, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(recovery_restore_stats{kubernetes_namespace=\"$namespace\", stat=~\".*ok.*\", stat!~\".*streams.*\"}) by (source, stat) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Azul Events Restored Issues",
   "type": "timeseries",
   "description": "Number of streams that have failed to be restored correctly for some reason.\n(Note these stats can be collected very slowly (once every 30minutes))",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "sum by(source, stat) (recovery_restore_stats{kubernetes_namespace=\"$namespace\", stat!~\".*ok.*\", stat!~\".*streams.*\"}) > 0",
     "legendFormat": "{{source}}-{{stat}}"
    }
   ]
  },
  {
   "title": "Events Restored",
   "type": "table",
   "description": "Tracks individual event source and event_types have completely been restored.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "clamp_max(sum(recovery_total_event_types_for_source{kubernetes_namespace=\"$namespace\"}) by (source)-sum(recovery_completed_event_types_for_source{kubernetes_namespace=\"$namespace\"}) by (source), 10)",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}