{{- define "harden.opensearch.container" -}}
allowPrivilegeEscalation: false
# FUTURE: read-only hardening https://github.com/opensearch-project/helm-charts/issues/330
# readOnlyRootFilesystem: true
capabilities:
  drop: ["ALL"]
  add: ["NET_BIND_SERVICE"]
runAsNonRoot: true
seccompProfile:
  type: RuntimeDefault
{{- end }}
