{
 "title": "Kafka Usage",
 "description": "Show all kafka usage, filter topics with less than 1mb of data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kafka",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Events - Kafka cluster disk usage\r\nThis dashboard displays the overall disk usage of all Kafka cluster infrastructure<br>"
   }
  },
  { "title": "Kafka Cluster - $kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "kafka" },
  {
   "title": "Total Usage",
   "type": "stat",
   "description": "Total disk usage",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{kubernetes_namespace=\"$kafka\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "By Partition",
   "type": "gauge",
   "description": "Disk usage by partition",
   "gridPos": { "h": 12, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(100,sum(label_replace(kafka_log_log_size{topic=~\"[^_].*\",kubernetes_namespace=\"$kafka\"}, \"entitytype\", \"$1\", \"topic\", \"[^.]*.([^.]*).*\")) by (entitytype)) > 1024*1024",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "By Source",
   "type": "gauge",
   "description": "Disk usage by source",
   "gridPos": { "h": 12, "w": 9, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(100,sum(label_replace(kafka_log_log_size{topic=~\"[^_].*\",kubernetes_namespace=\"$kafka\"}, \"entitytype\", \"$1\", \"topic\", \"[^.]*.[^.]*.([^.]*).*\")) by (entitytype)) > 1024*1024",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{kubernetes_namespace=\"$kafka\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_log_log_size{kubernetes_namespace=\"$kafka\"}) by (topic) > 1024*1024",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}