{
 "title": "Topic Reprocessing",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(dispatcher_events_fetched_total,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays the progress\nof historical/running reprocessor(s).\n\n'All Topics Finished'=Yes indicates that all\npartitions have been processed at\nleast once.\nAs dispatcher and reprocessor use the same destination prefix, \nthis indicates that reprocessing is complete and can be disabled safely.\n"
   }
  },
  {
   "title": "All Topics Finished",
   "type": "stat",
   "description": "If Yes, then it is safe to disable the kafka reprocessor migration.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(reprocessor_eof{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Reprocessed",
   "type": "timeseries",
   "description": "Displays total events that have been migrated. ",
   "gridPos": { "h": 25, "w": 19, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "reprocessor_event_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{source_topic}}"
    }
   ]
  },
  {
   "title": "Migrations In Progress",
   "type": "table",
   "description": "Shows current migrations in progress, and/or stalled migrations",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "reprocessor_eof{kubernetes_namespace=\"$namespace\"} <1\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migrations Completed",
   "type": "table",
   "description": "Shows topics from which all events have been read.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "reprocessor_eof{kubernetes_namespace=\"$namespace\"}>0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}