{{- if .Values.kafka.enable }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: nodes
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        {{ .Values.kafka.storage | toYaml | nindent 8 }}
  resources:
    {{- toYaml .Values.kafka.resources | nindent 4 }}
  jvmOptions:
    {{- toYaml .Values.kafka.jvmOptions | nindent 4 }}
  template:
    pod:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      metadata:
        annotations:
          prometheus.io/port: "9404"
          prometheus.io/path: "/metrics"
          prometheus.io/scrape: "true"
          {{- with $.Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}          
    kafkaContainer:
      {{- include "harden.container" . | nindent 6 }}
    initContainer:
      {{- include "harden.container" . | nindent 6 }}

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    metadataVersion: {{ .Values.kafka.metadataVersion }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      {{ .Values.kafka.clusterConfig | toYaml | nindent 6 }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.kafka.name }}-metrics
          key: kafka-metrics-config.yaml
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            helm.sh/resource-policy: "keep"
            argocd.argoproj.io/sync-options: "Prune=false"
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "250m"
        limits:
          memory: 256Mi
          cpu: "250m"
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "250m"
        limits:
          memory: 256Mi
          cpu: "250m"
    template:
      userOperatorContainer:
        {{- include "harden.container" . | nindent 8 }}
      topicOperatorContainer:
        {{- include "harden.container" . | nindent 8 }}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/port: "9404"
            prometheus.io/path: "/metrics"
            prometheus.io/scrape: "true"
      container:
        {{- include "harden.container" . | nindent 8 }}
    resources:
      requests:
        memory: 256Mi
        cpu: "500m"
      limits:
        memory: 256Mi
        cpu: "500m"

{{- end }}
